# Generated by Django 4.2.5 on 2023-10-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0002_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='type',
            field=models.CharField(choices=[('پرداخت', 'پرداخت'), ('دریافت', 'دریافت')], default='pay', max_length=50),
        ),
    ]
