# Generated by Django 4.2.5 on 2023-09-23 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0002_money_payment_type_payment_manager_employee_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('mainstate', models.CharField(max_length=20)),
                ('currentstate', models.CharField(max_length=20)),
                ('passport', models.IntegerField(null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('passportImage', models.ImageField(blank=True, null=True, upload_to='document/')),
                ('cardImage', models.ImageField(blank=True, null=True, upload_to='document/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isprocess', models.BooleanField(default=False)),
                ('isapproved', models.BooleanField(default=False)),
                ('ispayed', models.BooleanField(default=False)),
                ('isdone', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_tour.customer')),
            ],
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VisaRecivedDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.CharField(max_length=60, null=True)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_tour.visa')),
            ],
        ),
        migrations.CreateModel(
            name='visaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.FloatField(null=True)),
                ('Blockaddress', models.CharField(max_length=50)),
                ('Blockimage', models.ImageField(blank=True, null=True, upload_to='document/')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_tour.visa')),
            ],
        ),
        migrations.AddField(
            model_name='visa',
            name='visaType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_tour.visatype'),
        ),
    ]
