# Generated by Django 4.2.5 on 2023-10-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0002_visa_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='ccv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='cr',
            field=models.BooleanField(default=False),
        ),
    ]
