# Generated by Django 4.2.5 on 2023-10-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0003_bill_ccv_bill_cr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='ccv',
            new_name='cv',
        ),
    ]
