# Generated by Django 4.2.5 on 2023-10-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0003_alter_notes_date_alter_notes_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
