# Generated by Django 4.2.5 on 2023-09-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0003_customer_location_visa_visatype_visareciveddoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='money_type',
            field=models.CharField(max_length=20),
        ),
    ]
