# Generated by Django 4.2.5 on 2023-09-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0004_alter_money_money_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
