# Generated by Django 4.2.5 on 2023-10-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0006_otherbill_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='mainprice',
            field=models.FloatField(default=0),
        ),
    ]
