# Generated by Django 4.2.5 on 2023-10-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0007_bill_mainprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
