# Generated by Django 4.2.5 on 2023-09-27 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0007_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_tour.employee'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
