# Generated by Django 4.2.5 on 2023-09-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0008_customer_employee_alter_customer_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
