# Generated by Django 4.2.5 on 2023-09-27 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0009_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
