# Generated by Django 4.2.5 on 2023-10-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0009_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='peopleNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bill',
            name='phone',
            field=models.CharField(default='07....', max_length=15),
        ),
    ]
