# Generated by Django 4.2.7 on 2023-11-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0010_bill_peopleno_bill_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
