# Generated by Django 4.2.5 on 2023-09-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0010_alter_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='visa',
            name='saveddate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visa',
            name='visapdf',
            field=models.FileField(null=True, upload_to='VisaPdfFiles/'),
        ),
        migrations.AlterField(
            model_name='visapayment',
            name='Blockaddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visapayment',
            name='Blockimage',
            field=models.ImageField(blank=True, null=True, upload_to='BlockImage/'),
        ),
        migrations.AddField(
            model_name='visa',
            name='emailby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel_tour.ouremail'),
            preserve_default=False,
        ),
    ]
