# Generated by Django 4.2.5 on 2023-09-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0011_ouremail_visa_saveddate_visa_visapdf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visapayment',
            old_name='Blockaddress',
            new_name='blockAddress',
        ),
        migrations.RenameField(
            model_name='visapayment',
            old_name='Blockimage',
            new_name='blockImage',
        ),
        migrations.AddField(
            model_name='visatype',
            name='money',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel_tour.money'),
            preserve_default=False,
        ),
    ]
