# Generated by Django 4.2.7 on 2023-11-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0011_bill_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='isprint',
            field=models.BooleanField(default=False),
        ),
    ]
