# Generated by Django 4.2.5 on 2023-09-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0012_rename_blockaddress_visapayment_blockaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='money',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel_tour.money'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visa',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
