# Generated by Django 4.2.5 on 2023-10-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0013_visa_money_visa_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visa',
            old_name='isdone',
            new_name='isproccessed',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='ispayed',
        ),
    ]
