# Generated by Django 4.2.5 on 2023-10-03 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0014_rename_isdone_visa_isproccessed_remove_visa_ispayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reciveddoc', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('price', models.FloatField()),
                ('payed', models.FloatField()),
                ('isdone', models.BooleanField(default=False)),
                ('money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_tour.money')),
                ('visatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_tour.visatype')),
            ],
        ),
    ]
