# Generated by Django 4.2.5 on 2023-10-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0015_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
