# Generated by Django 4.2.5 on 2023-11-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0016_qararrdad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qararrdad',
        ),
    ]
