# Generated by Django 4.2.5 on 2023-10-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0016_bill_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visa',
            old_name='isproccessed',
            new_name='iscomplate',
        ),
        migrations.AddField(
            model_name='visa',
            name='isrejected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='registerPayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.FloatField(null=True)),
                ('money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_tour.money')),
                ('visa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_tour.visa')),
            ],
        ),
    ]
