# Generated by Django 4.2.5 on 2023-12-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0018_qararrdad'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='Otherdocs',
            field=models.FileField(default=None, null=True, upload_to='VisaPdfFiles/'),
        ),
    ]
