# Generated by Django 4.2.5 on 2023-12-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tour', '0022_alter_visa_saveddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='note',
            field=models.CharField(default='درج نگردیده', max_length=50),
        ),
    ]
